import LegalPage from '../components/LegalPage'
import { EMAIL } from '../site'

// NOTE: baseline terms copy. Have counsel review it before launch and update the
// "Last updated" date when they do.
const SECTIONS = [
  {
    heading: 'These terms',
    paragraphs: [
      'By using yuiops.com you agree to what is on this page. If you engage us for work, that engagement is governed by a separate written agreement, and where the two disagree, the engagement agreement wins.',
    ],
  },
  {
    heading: 'The free diagnostics',
    paragraphs: [
      'The Operations Health Check and Find My Bottleneck are free tools that produce an automated assessment from the answers you give. They are generated by a language model, they are a starting point for a conversation, and they are not professional, financial, legal, or accounting advice.',
      'Do not make an irreversible business decision on the basis of a two-minute quiz. Results are provided as-is, with no warranty of accuracy.',
    ],
  },
  {
    heading: 'Acceptable use',
    paragraphs: [
      'Use this site for its intended purpose. Do not attempt to break, overload, scrape at scale, or gain unauthorized access to it or the services behind it, and do not submit anything unlawful through our forms.',
      'We may rate-limit or block traffic that threatens the availability of the site for everyone else.',
    ],
  },
  {
    heading: 'Pricing shown on this site',
    paragraphs: [
      'The prices on our pricing section describe our standard packages and are provided for information. Scope, timeline, and price for any actual engagement are confirmed in writing before work begins, and custom engagements are quoted directly.',
    ],
  },
  {
    heading: 'Our content',
    paragraphs: [
      'The text, design, and code of this site belong to us, except where noted. Work we build for a client is governed by that client’s engagement agreement, not by this page.',
    ],
  },
  {
    heading: 'Limitation of liability',
    paragraphs: [
      'To the extent the law allows, we are not liable for indirect or consequential losses arising from your use of this site or of the free diagnostics. Nothing here limits liability that cannot lawfully be limited.',
    ],
  },
  {
    heading: 'Changes and contact',
    paragraphs: [
      'We may update these terms; the date at the top of this page tells you when we last did.',
      `Questions go to ${EMAIL}.`,
    ],
  },
]

export default function TermsPage() {
  return (
    <LegalPage
      testId="terms-page"
      title="Terms of use"
      metaTitle="Terms of use | Yui"
      description="The terms that govern use of yuiops.com and the free operations diagnostics on it."
      path="/terms"
      updated="September 2026"
      intro="Plain terms for a small marketing site: use it sensibly, treat the free diagnostics as a conversation starter rather than advice, and read your engagement agreement for anything we build."
      sections={SECTIONS}
    />
  )
}
